# Generated by Django 4.2.23 on 2025-08-01 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[(0, 'TO DO'), (1, 'IN PROGRESS'), (2, 'COMPLETE')], max_length=20)),
                ('priority', models.CharField(choices=[(0, 'LOW PRIORITY'), (1, 'MIDDLE PRIORITY'), (2, 'HIGH PRIORITY')], max_length=20)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
